#:schema ./.aviutl2-cli/aviutl2.schema.json
# 設定ファイルについては https://github.com/sevenc-nanashi/aviutl2-cli を参照してください。
[project]
id = "vandojapan.comfont"
name = "comfont"
version = "0.2.0"

[development]
aviutl2_version = "latest"

[catalog]
id = "vandojapan.comfont"
description_path = "readme.md"
download_repo = { owner = "vandojapan", repo = "comfont" }

[artifacts.compositefont-editor-aux2]
destination = "Plugin/comfont.aux2"
placement_method = "copy"

[artifacts.compositefont-editor-aux2.profiles.debug]
build = "cargo build -p compositefont-editor-plugin"
source = "target/debug/compositefont_editor.dll"

[artifacts.compositefont-editor-aux2.profiles.release]
build = "cargo build -p compositefont-editor-plugin --release"
source = "target/release/compositefont_editor.dll"

[artifacts.compositefont-test-script]
destination = "Script/@compositefont-test.obj2"
placement_method = "copy"

[artifacts.compositefont-test-script.profiles.debug]
source = "scripts/@compositefont-test.obj2"

[artifacts.compositefont-test-script.profiles.release]
enabled = false

[artifacts.compositefont-subtitle-object]
destination = "Alias/合成フォント字幕.object"
placement_method = "copy"

[artifacts.compositefont-subtitle-object.profiles.debug]
source = "scripts/合成フォント字幕.object"

[artifacts.compositefont-subtitle-object.profiles.release]
source = "scripts/合成フォント字幕.object"

[artifacts.compositefont-name-object]
destination = "Alias/合成フォント名前表示.object"
placement_method = "copy"

[artifacts.compositefont-name-object.profiles.debug]
source = "scripts/合成フォント名前表示.object"

[artifacts.compositefont-name-object.profiles.release]
source = "scripts/合成フォント名前表示.object"

[artifacts.compositefont-text-object]
destination = "Alias/合成フォントテキスト.object"
placement_method = "copy"

[artifacts.compositefont-text-object.profiles.debug]
source = "scripts/合成フォントテキスト.object"

[artifacts.compositefont-text-object.profiles.release]
source = "scripts/合成フォントテキスト.object"
